ARG from=nickodema/hsl_2022:general

FROM ${from}

ENV WS=/workspace
ENV ROS_DISTRO=humble

RUN echo "source ${WS}/install/setup.bash" >> ~/.bashrc
RUN echo "cd ${WS}" >> ~/.bashrc

RUN apt update -y

RUN DEBIAN_FRONTEND=noninteractive apt install -y python3-pip
RUN DEBIAN_FRONTEND=noninteractive apt install -y vim emacs nano

RUN python3 -m pip install setuptools==58.2.0

RUN apt install -y \
    ros-${ROS_DISTRO}-slam-toolbox \
    ros-${ROS_DISTRO}-navigation2  \
    ros-${ROS_DISTRO}-nav2-bringup \
    ros-${ROS_DISTRO}-tf2-geometry-msgs

RUN python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN python3 -m pip install opencv-python qreader zbar
