ARG base_img

FROM ${base_img}

RUN apt update
RUN apt install ros-humble-nav2-msgs
RUN apt install ros-humble-slam-toolbox
RUN apt install ros-humble-nav2-bringup

### ---------------------------------------------------------------------- #
