ARG base_img

FROM ${base_img}

RUN apt update -y
RUN apt install -y ros-humble-nav2-msgs ros-humble-nav2-bringup ros-humble-slam-toolbox

### ---------------------------------------------------------------------- #
