ARG base_img

FROM ${base_img}

RUN apt update
RUN apt install ros-humble-nav2-msgs ros-humble-nav2-bringup ros-humble-slam-toolbox

### ---------------------------------------------------------------------- #
