ARG from=nickodema/hsl_2022:general

FROM ${from}

ENV WS=/workspace
ENV ROS_DISTRO=humble

RUN echo "source ${WS}/install/setup.bash" >> ~/.bashrc
RUN echo "cd ${WS}" >> ~/.bashrc

RUN echo "alias s='source ./install/setup.bash'" >> ~/.bashrc
RUN echo "alias l='clear'" >> ~/.bashrc

RUN apt update -y

RUN DEBIAN_FRONTEND=noninteractive apt install -y python3-pip
RUN DEBIAN_FRONTEND=noninteractive apt install -y vim

RUN python3 -m pip install setuptools==58.2.0

RUN apt install -y \
    ros-${ROS_DISTRO}-slam-toolbox \
    ros-${ROS_DISTRO}-navigation2  \
    ros-${ROS_DISTRO}-nav2-bringup \
    ros-${ROS_DISTRO}-tf2-geometry-msgs \
    ros-${ROS_DISTRO}-zbar-ros \
    ros-${ROS_DISTRO}-gazebo-ros \
    ros-${ROS_DISTRO}-gazebo-plugins
