/**:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: true
    costmap_topic: map
    costmap_updates_topic: map_updates
    visualize: false
    planner_frequency: 10.0
    progress_timeout: 40.0
    potential_scale: 3.0
    orientation_scale: 0.0
    gain_scale: 3.0
    transform_tolerance: 0.9
    min_frontier_size: 0.2